### ISSUE TITLE
PermissionError at /blog/author/shahidul/

### ISSUE THREAD

**Issue by shahidulsir** [TareqMonwer/Django-School-Management#104]
Card alignment is not correct

![image](https://user-images.githubusercontent.com/61648420/106439562-08336e80-64a2-11eb-89a7-16f423c7a2af.png)
![image](https://user-images.githubusercontent.com/61648420/106446838-f0acb380-64aa-11eb-932a-84d823124d50.png)

**Comment by TareqMonwer** [comment]
The error is now fixed! It's just permission error from the server.
