### ISSUE TITLE
Unable to Migrate

### ISSUE THREAD

**Issue by gitamitgit** [TareqMonwer/Django-School-Management#143]
Hi ,

**STEPS:**
- clone reepository
- python3 -m pipenv shell
- pip install -r requirements.txt
- python manage.py migrate

Unable to migrate it showing me below error:
`django.core.exceptions.ImproperlyConfigured: Cannot import 'blog.articles'. Check that 'articles.apps.ArticlesConfig.name' is correct.`

Need your help to run this project  

Thanks

**Comment by mathgenius1991712** [comment]
I got the similar error

I cloned the repository, created virtual environment, installed dependencies

And when I ran "python manage.py makemigrations" I get the following

![image](https://github.com/TareqMonwer/Django-School-Management/assets/126612071/d29fbaaf-5c73-4e92-849f-cf15ffafe461)

**Comment by TareqMonwer** [comment]
Hey @mathgenius1991712, It's ok to for `makemigrations` you just need to run `python manage.py migrate` command to bring the changes into your database.

**Comment by mathgenius1991712** [comment]
Thanks, @TareqMonwer
