### ISSUE TITLE
I am facing issue while cloning the repo:

### ISSUE THREAD

**Issue by Kushaldotel** [TareqMonwer/Django-School-Management#164]
### Discussed in https://github.com/TareqMonwer/Django-School-Management/discussions/163

<div type='discussions-op-text'>

<sup>Originally posted by **Kushaldotel** December 26, 2023</sup>
PS E:\School-Management\B> git clone https://github.com/TareqMonwer/Django-School-Management.git
Cloning into 'Django-School-Management'...
remote: Enumerating objects: 9578, done.
remote: Counting objects: 100% (2270/2270), done.
remote: Compressing objects: 100% (1894/1894), done.
error: RPC failed; curl 92 HTTP/2 stream 5 was not closed cleanly: CANCEL (err 8)
error: 3871 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output
PS E:\School-Management\B> git clone --verbose https://github.com/TareqMonwer/Django-School-Management.git
>>
Cloning into 'Django-School-Management'...
POST git-upload-pack (185 bytes)
POST git-upload-pack (812 bytes)
remote: Enumerating objects: 9578, done.
remote: Counting objects: 100% (2270/2270), done.
remote: Compressing objects: 100% (1894/1894), done.
error: RPC failed; curl 92 HTTP/2 stream 5 was not closed cleanly: CANCEL (err 8)
error: 5652 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output
PS E:\School-Management\B> git clone --depth 1 https://github.com/TareqMonwer/Django-School-Management.git
>> 
Cloning into 'Django-School-Management'...
remote: Enumerating objects: 4408, done.
remote: Counting objects: 100% (4408/4408), done.
remote: Compressing objects: 100% (3922/3922), done.
error: RPC failed; curl 92 HTTP/2 stream 5 was not closed cleanly: CANCEL (err 8)
error: 2608 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output

My network is fine and GitHub is also responding. But getting issues during cloning:
PS E:\School-Management\B> ping github.com
>> 

Pinging github.com [20.205.243.166] with 32 bytes of data:
Reply from 20.205.243.166: bytes=32 time=80ms TTL=117
Reply from 20.205.243.166: bytes=32 time=81ms TTL=117
Reply from 20.205.243.166: bytes=32 time=80ms TTL=117
Reply from 20.205.243.166: bytes=32 time=83ms TTL=117

Ping statistics for 20.205.243.166:
    Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 80ms, Maximum = 83ms, Average = 81ms
PS E:\School-Management\B> </div>

**Comment by TareqMonwer** [comment]
I believe you need to use SSH link (i.e: `git clone git@github.com:TareqMonwer/Django-School-Management.git`), not the HTTP one.
