### ISSUE TITLE
Add `course` app for classes for student promotion, attendance etc.

### ISSUE THREAD

**Issue by TareqMonwer** [TareqMonwer/Django-School-Management#19]
A `class` app should be responsible for students attendance and yearly/semester-wise/course promotion.
Attenace wil be in common between student and course. Courses can have multiple groups/sections.

We can use our Combination model inside admin_tools app in order to create active classes.

**Comment by tanvirstreame** [comment]
Please see here https://github.com/TareqMonwer/Django-School-Management/pull/22

**Comment by TareqMonwer** [comment]
fixed here #22
