### ISSUE TITLE
Create a command to populate database

### ISSUE THREAD

**Issue by Marlysson** [TareqMonwer/Django-School-Management#37]
Run the command like this to don't run "out of" a django environment. 

> manage.py populate students|teachers|departments

Resource could be students, departments, teachers or whatever we want.

*Motivation:* Remove the bundle of getting up the django environment like django.setup()

Can I take this...

**Comment by tanvirstreame** [comment]
Sure.. 
You can take this

**Comment by TareqMonwer** [comment]
Hello @Marlysson 
If you can do it please make a PR. We'll be glad. Otherwise, I should close the issue.
Let us know :).
