### ISSUE TITLE
Environment database files

### ISSUE THREAD

**Issue by talesmm14** [TareqMonwer/Django-School-Management#42]
django.db.migrations.exceptions.NodeNotFoundError: Migration course.0004_auto_20191214_2233 dependencies reference nonexistent parent node ('course', '0003_auto_20191213_1812')

dependencies automatically generated by 'migrate' that shouldn't be in the repository?

Am I wrong or shouldn't these files have been introduced into the repositories? '0003_auto_20191213_1812'

**Comment by tanvirstreame** [comment]
How did you solve this?

**Comment by talesmm14** [comment]
I removed the '0003_auto_20191213_1812' document, so I made makemigrations again.
It looks like someone removed the '0003_auto_20191213_1812' during some commit!
