### ISSUE TITLE
migration error

### ISSUE THREAD

**Issue by usmanazam96** [TareqMonwer/Django-School-Management#43]
django.db.migrations.exceptions.NodeNotFoundError: Migration result.0003_auto_20191125_0414 dependencies reference nonexistent parent node ('students', '0004_auto_20191125_0353')

**Comment by nikhillad01** [comment]
Hey, @usmanazam96 delete the migrations,_pycache_  folders from all the apps/sub-folders.

**Comment by TareqMonwer** [comment]
> Hey, @usmanazam96 delete the migrations,_pycache_ folders from all the apps/sub-folders.
> Run the makemigrations command for all the apps: python3 manage.py makemigrations account
> Then migrate

Thanks, since this solution works perfectly, I'm closing this issue.
